### ISSUE TITLE
Got problems when using Gitlab+Hexo

### ISSUE THREAD

**Issue by GitHubd3b7c** [LEAFERx/hexo-leancloud-counter-security#14]
I'm using Gitlab + Hexo instead of Github page but there something wrong with it.
![image](https://user-images.githubusercontent.com/33088850/57858877-6f1f7880-7824-11e9-8211-7a258a9c0506.png)
just like this

**Comment by GitHubd3b7c** [comment]
I think there is the problems 
![image](https://user-images.githubusercontent.com/33088850/57858958-9aa26300-7824-11e9-95f0-826979d3f35d.png)
Cause Gitlab use CI/DI 
Don't kown what should I do , should I just turn `security: true` into `false` ?

**Comment by sli1989** [comment]
what do u mean? Documentation how to set the counter up and running safely aviable in [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/LEANCLOUD-COUNTER-SECURITY.md) or Chinese languages. please check this.

the deployer is added in **site config file**.

[gitlab CI](https://theme-next.org/docs/getting-started/deployment) seems has no this function.
