### ISSUE TITLE
文章标题中出现 ""  时 JSON 解析会出现错误

### ISSUE THREAD

**Issue by xiang578** [LEAFERx/hexo-leancloud-counter-security#15]
文章标题包含双引号时，JSON 解析会错，插件无法继续运行。
暂时通过删除标题中的双引号时解决。

**Comment by 1v9** [comment]
需要转义双引号。
这里提供两个粗糙的办法，仅供参考：

第一种是将
https://github.com/theme-next/hexo-leancloud-counter-security/blob/d65c65720fa14e91574e717dc190d4946a71853a/index.js#L162

替换为 `title: x.title.replace(/\"/g, '\\\"'),`，不过这么搞一是修改后的插件并没有完整解决双引号问题，二是 `hexo g` 生成的 `data-flag-title` 属性值也包含双引号，直接导致 gulp-htmlmin 失败：

```html
<span id="/post/post-title-contains-double-quotes.html" class="leancloud_visitors" data-flag-title="文章" 标题"包含双引号">
```

第二种是手动修改 JSON，人工转义，也不好。

建议按照你自己的做法，去了了事，双引号确实是个不和谐的东西。

**Comment by 1v9** [comment]
https://1v9.im/post/post-title-contains-double-quotes.html

<blockquote><div><img src="/image/favicon-16x16.png?v=7.1.2" height="14"> 1v9's Blog</div><div><strong><a href="https://1v9.im/post/post-title-contains-double-quotes.html">文章"标题"包含双引号</a></strong></div><div>https://github.com/theme-next/hexo-leancloud-counter-security/issues/15</div></blockquote>

**Comment by LEAFERx** [comment]
JSON.stringify 应该已经转义了不会出现这样的情况呀
（建议使用中文括号XD
