### ISSUE TITLE
[feature] help update leancloud rest api

### ISSUE THREAD

**Issue by myoss** [LEAFERx/hexo-leancloud-counter-security#4]
经常出现类似的网络问题， [ERR_CONNECTION_REST](https://forum.leancloud.cn/t/err-connection-reset/16976)，从官方社区论坛中了解到，和访问的域名有关系，他们已经更新了新的 `REST API`

[API 域名近日出现间歇性解析失败的说明](https://forum.leancloud.cn/t/leancloud-api/16234)
[更安全的鉴权方式](https://leancloud.cn/docs/rest_api.html#hash-1794863242)

**Comment by LEAFERx** [comment]
will fix as soon as i have time
Pr's really appreciated

**Comment by LEAFERx** [comment]
https://github.com/theme-next/hexo-theme-next/pull/381
已经完成重构
