### ISSUE TITLE
Counter not initialized! See more at console err msg

### ISSUE THREAD

**Issue by abcdGJJ** [LEAFERx/hexo-leancloud-counter-security#5]
I have followed the article [Leancloud访客统计插件重大安全漏洞修复指南](https://leaferx.online/2018/02/11/lc-security) and finished first four steps, but I got an error 'Counter not initialized! See more at console err msg'.

Is something wrong? My environment is localhost

**Comment by LEAFERx** [comment]
Did u add localhost to your whitelist？

**Comment by abcdGJJ** [comment]
yes, of course

**Comment by LEAFERx** [comment]
Oh I know, you must have not deployed right? This plugin will sync the post list to leancloud only when you run deploy. Try deploy it, and you may see it works fine.

**Comment by abcdGJJ** [comment]
@LEAFERx Yeah, it's working
