### ISSUE TITLE
Generate wrong url for each post for leancloud counter when running site in a subdirectory

### ISSUE THREAD

**Issue by wuliuxiansheng** [LEAFERx/hexo-leancloud-counter-security#6]
The url for a post should be `/blog/post` after deploy if running site in a subdirectory that is `domain/blog/` but the url generated is `/post`.

**Comment by LEAFERx** [comment]
@wuliuxiansheng try checkout dev branch and test if it works fine. I don't have env to test for now.

**Comment by wuliuxiansheng** [comment]
@LEAFERx It still generates wrong urls.

**Comment by LEAFERx** [comment]
Could you give me examples for this version? And what's your roots variable in site _config.yml?

**Comment by wuliuxiansheng** [comment]
It generate the same urls with the master branch and I set the root to be /~chaoliu/ in my _config.yml file.

**Comment by LEAFERx** [comment]
what about now? I've tested it and it works fine.

**Comment by wuliuxiansheng** [comment]
It is not working. Now the url for all post become the root.

**Comment by LEAFERx** [comment]
sry it's my bad. I'm not pushing the right code. Now it should work. Pls try?

**Comment by wuliuxiansheng** [comment]
Great! It is working now. Thanks.

**Comment by LEAFERx** [comment]
Okay, I'll merge it into master.
