### ISSUE TITLE
Known low severity security vulnerability detected in randomatic < 3.0.0

### ISSUE THREAD

**Issue by ivan-nginx** [LEAFERx/hexo-leancloud-counter-security#7]
![image](https://user-images.githubusercontent.com/16944225/46731303-9f99a580-cc8a-11e8-99fc-a85bce0e6b81.png)

![image](https://user-images.githubusercontent.com/16944225/46731332-b3dda280-cc8a-11e8-8b35-fe6318455d72.png)

**Comment by LEAFERx** [comment]
I'm thinking delete package-lock.json, what do you think?
Main reason is it doesn't matter and our npm registry may varies so maybe it's unconvenient for developing.

**Comment by ivan-nginx** [comment]
As you wish, i just reported this vulns.

**Comment by stevenjoezhang** [comment]
`package-lock.json` deleted in https://github.com/theme-next/hexo-leancloud-counter-security/commit/5696859824cee92d8383664885754d9fc3a5d158
